name: expense_manager
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Atwic
      fonts:
        - asset: assets/fonts/Atwic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Atwic-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Atwic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Atwic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Atwic-Black.ttf
          weight: 900

